name: Tests PHPUnit in environments

on: [pull_request]

jobs:
  php8-laravel-latest-phpunit-mysql:
    runs-on: ubuntu-latest
    container:
      image: escolalms/php:8

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: database
          MYSQL_PASSWORD: password
          MYSQL_USER: username
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Instantiate package
        uses: actions/checkout@v2

      - name: Setup environment
        run: cp env/mysql/* .

      - name: Update composer
        run: composer update

      - name: Clear config
        run: vendor/bin/testbench config:clear

      - name: Publish things
        run: vendor/bin/testbench migrate:fresh

      - name: Run tests
        run: vendor/bin/phpunit

  php74-laravel-latest-phpunit-mysql:
    runs-on: ubuntu-latest
    container:
      image: escolalms/php:7.4

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: database
          MYSQL_PASSWORD: password
          MYSQL_USER: username
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Instantiate package
        uses: actions/checkout@v2

      - name: Setup environment
        run: cp env/mysql/* .

      - name: Update composer
        run: composer update

      - name: Clear config
        run: vendor/bin/testbench config:clear

      - name: Publish things
        run: vendor/bin/testbench migrate:fresh

      - name: Run tests
        run: vendor/bin/phpunit

  php74-laravel-latest-phpunit-postgres:
    runs-on: ubuntu-latest
    container:
      image: escolalms/php:7.4

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
          TZ: Europe/Warsaw
        ports:
          - 5432:5432

    steps:
      - name: Instantiate package
        uses: actions/checkout@v2

      - name: Update composer
        run: composer update

      - name: Setup environment
        run: cp env/postgres/* .

      - name: Clear config
        run: vendor/bin/testbench config:clear

      - name: Publish things
        run: vendor/bin/testbench migrate:fresh

      - name: Run tests
        run: vendor/bin/phpunit

  php73-laravel-8-phpunit-postgres:
    runs-on: ubuntu-latest
    container:
      image: escolalms/php:7.3

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
          TZ: Europe/Warsaw
        ports:
          - 5432:5432

    steps:
      - name: Instantiate package
        uses: actions/checkout@v2

      - name: Update composer
        run: composer require laravel/laravel:^8 orchestra/testbench:^6

      - name: Update composer
        run: composer update

      - name: Setup environment
        run: cp env/postgres/* .

      - name: Clear config
        run: vendor/bin/testbench config:clear

      - name: Publish things
        run: vendor/bin/testbench migrate:fresh

      - name: Run tests
        run: vendor/bin/phpunit

  php73-laravel-7-phpunit-postgres:
    runs-on: ubuntu-latest
    container:
      image: escolalms/php:7.3

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test
          TZ: Europe/Warsaw
        ports:
          - 5432:5432

    steps:
      - name: Instantiate package
        uses: actions/checkout@v2

      - name: Update composer
        run: composer require laravel/laravel:^7 orchestra/testbench:^5

      - name: Update composer
        run: composer update

      - name: Setup environment
        run: cp env/postgres/* .

      - name: Clear config
        run: vendor/bin/testbench config:clear

      - name: Publish things
        run: vendor/bin/testbench migrate:fresh

      - name: Run tests
        run: vendor/bin/phpunit
### TODO add behat tests here
